### PR TITLE
COBOL Language Support v0.12 release + update whats new section

### PR DESCRIPTION
**Pull request by zeibura**
Added a new step to the COBOL workflow to include the copybook retrieval feature, let me know what you think.

### CODE REVIEW

**Comment by zeibura** [comment]
@zimlu02 changed in latest commit

**Comment by zeibura** [comment]
This can be merged along with v0.12 of COBOL Language Support. Upon merging please check if there is a new version of Zowe Explorer (newer than 1.6) to add to the Whats New section.

**Comment by DStatWriter** [comment]
Zeb advised: "This can be merged along with v0.12 of COBOL Language Support. Upon merging please check if there is a new version of Zowe Explorer (newer than 1.6) to add to the Whats New section."

Is there a new version for me to update to before publishing?

**Comment by fox0r** [comment]
opened  https://github.com/BroadcomMFD/code4z/pull/16 including Zeb'S changes

**Pull request closed without merging**
